// <auto-generated />
using CaseItau.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseItau.Infrastructure.Migrations
{
    [DbContext(typeof(FundsDbContext))]
    [Migration("20250625002838_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CaseItau.Domain.Entities.Fund", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Patrimony")
                        .HasColumnType("numeric");

                    b.Property<long>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Funds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ITAURF123",
                            Name = "ITAU JUROS RF +",
                            Patrimony = 5498731.54m,
                            TypeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Code = "ITAUMM999",
                            Name = "ITAU TREND MM",
                            Patrimony = 5m,
                            TypeId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ITAURF321",
                            Name = "ITAU LONGO PRAZO RF +",
                            Patrimony = 7875421.58m,
                            TypeId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Code = "ITAUAC546",
                            Name = "ITAU ACOES DIVIDENDO",
                            Patrimony = 66421254.83m,
                            TypeId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Code = "ITAURF555",
                            Name = "ITAU JUROS RF +",
                            Patrimony = 0m,
                            TypeId = 1L
                        });
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.FundType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("FundTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "RENDA FIXA"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "ACOES"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "MULTI MERCADO"
                        });
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.Fund", b =>
                {
                    b.HasOne("CaseItau.Domain.Entities.FundType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CaseItau.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<long>("FundId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("Cnpj");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");

                            b1.HasData(
                                new
                                {
                                    FundId = 1L,
                                    Value = "11222333444455"
                                },
                                new
                                {
                                    FundId = 2L,
                                    Value = "12222333444455"
                                },
                                new
                                {
                                    FundId = 3L,
                                    Value = "13222333444455"
                                },
                                new
                                {
                                    FundId = 4L,
                                    Value = "14222333444455"
                                },
                                new
                                {
                                    FundId = 5L,
                                    Value = "11222333444777"
                                });
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
