name: ASP.NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      SOLUTION_NAME: CaseItau.sln
      UNIT_TEST_PROJECT: tests/CaseItau.UnitTests/CaseItau.UnitTests.csproj
      INTEGRATION_TEST_PROJECT: tests/CaseItau.IntegrationTests/CaseItau.IntegrationTests.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_NAME }} --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test ${{ env.UNIT_TEST_PROJECT }} --configuration Release --no-build --logger trx

    - name: Run Integration Tests
      run: dotnet test ${{ env.INTEGRATION_TEST_PROJECT }} --configuration Release --no-build --logger trx
